apiVersion: v1
kind: Pod
metadata:
   name: two-tier-app-pod

spec:
 containers:
  - name: two-tier-app-ctr
    image: swaleha6/flaskapp:latest
    env:
      - name: MYSQL_HOST
        value: "mysql"
      - name: MYSQL_USER
        value: "admin"
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_DB
        value: "myDb"
    ports: 
      - containerPort: 5000
    imagePullPolicy: Always         
